<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Cricket" failures="13" tests="80" name="Default test" time="518.333" errors="0" timestamp="2025-01-11T21:43:22 CST">
  <testcase classname="testCases.Tree_TestCase" name="ABT" time="0.765"/>
  <testcase classname="testCases.Tree_TestCase" name="BST" time="1.662"/>
  <testcase classname="testCases.Tree_TestCase" name="BibaryTree" time="2.186"/>
  <testcase classname="testCases.Tree_TestCase" name="BinTreeTrav" time="0.969"/>
  <testcase classname="testCases.Tree_TestCase" name="EmptyTryeditorABT" time="7.835">
    <failure type="java.lang.AssertionError" message="Alert is not present">
      <![CDATA[java.lang.AssertionError: Alert is not present
at org.testng.Assert.fail(Assert.java:111)
at testCases.Tree_TestCase.EmptyTryeditorABT(Tree_TestCase.java:922)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- EmptyTryeditorABT -->
  <testcase classname="testCases.Tree_TestCase" name="EmptyTryeditorBST" time="2.276">
    <failure type="java.lang.AssertionError" message="Alert is not present">
      <![CDATA[java.lang.AssertionError: Alert is not present
at org.testng.Assert.fail(Assert.java:111)
at testCases.Tree_TestCase.EmptyTryeditorBST(Tree_TestCase.java:1004)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- EmptyTryeditorBST -->
  <testcase classname="testCases.Tree_TestCase" name="EmptyTryeditorBT" time="2.369">
    <failure type="java.lang.AssertionError" message="Alert is not present">
      <![CDATA[java.lang.AssertionError: Alert is not present
at org.testng.Assert.fail(Assert.java:111)
at testCases.Tree_TestCase.EmptyTryeditorBT(Tree_TestCase.java:529)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- EmptyTryeditorBT -->
  <testcase classname="testCases.Tree_TestCase" name="EmptyTryeditorBinTreeTrav" time="1.978">
    <failure type="java.lang.AssertionError" message="Alert is not present">
      <![CDATA[java.lang.AssertionError: Alert is not present
at org.testng.Assert.fail(Assert.java:111)
at testCases.Tree_TestCase.EmptyTryeditorBinTreeTrav(Tree_TestCase.java:766)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- EmptyTryeditorBinTreeTrav -->
  <testcase classname="testCases.Tree_TestCase" name="EmptyTryeditorIBST" time="1.789">
    <failure type="java.lang.AssertionError" message="Alert is not present">
      <![CDATA[java.lang.AssertionError: Alert is not present
at org.testng.Assert.fail(Assert.java:111)
at testCases.Tree_TestCase.EmptyTryeditorIBST(Tree_TestCase.java:1085)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- EmptyTryeditorIBST -->
  <testcase classname="testCases.Tree_TestCase" name="EmptyTryeditorIBT" time="2.436">
    <failure type="java.lang.AssertionError" message="Alert is not present">
      <![CDATA[java.lang.AssertionError: Alert is not present
at org.testng.Assert.fail(Assert.java:111)
at testCases.Tree_TestCase.EmptyTryeditorIBT(Tree_TestCase.java:844)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- EmptyTryeditorIBT -->
  <testcase classname="testCases.Tree_TestCase" name="EmptyTryeditorImpinBT" time="3.151">
    <failure type="java.lang.AssertionError" message="Alert is not present">
      <![CDATA[java.lang.AssertionError: Alert is not present
at org.testng.Assert.fail(Assert.java:111)
at testCases.Tree_TestCase.EmptyTryeditorImpinBT(Tree_TestCase.java:687)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- EmptyTryeditorImpinBT -->
  <testcase classname="testCases.Tree_TestCase" name="EmptyTryeditorOverview" time="1.862">
    <failure type="java.lang.AssertionError" message="Alert is not present">
      <![CDATA[java.lang.AssertionError: Alert is not present
at org.testng.Assert.fail(Assert.java:111)
at testCases.Tree_TestCase.EmptyTryeditorOverview(Tree_TestCase.java:127)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- EmptyTryeditorOverview -->
  <testcase classname="testCases.Tree_TestCase" name="EmptyTryeditorTerminologies" time="3.796">
    <failure type="java.lang.AssertionError" message="Alert is not present">
      <![CDATA[java.lang.AssertionError: Alert is not present
at org.testng.Assert.fail(Assert.java:111)
at testCases.Tree_TestCase.EmptyTryeditorTerminologies(Tree_TestCase.java:210)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- EmptyTryeditorTerminologies -->
  <testcase classname="testCases.Tree_TestCase" name="EmptyTryeditorTravelsIllus" time="4.081">
    <failure type="java.lang.AssertionError" message="Alert is not present">
      <![CDATA[java.lang.AssertionError: Alert is not present
at org.testng.Assert.fail(Assert.java:111)
at testCases.Tree_TestCase.EmptyTryeditorTravelsIllus(Tree_TestCase.java:451)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- EmptyTryeditorTravelsIllus -->
  <testcase classname="testCases.Tree_TestCase" name="EmptyTryeditorTreeTraversals" time="1.688">
    <failure type="java.lang.AssertionError" message="Alert is not present">
      <![CDATA[java.lang.AssertionError: Alert is not present
at org.testng.Assert.fail(Assert.java:111)
at testCases.Tree_TestCase.EmptyTryeditorTreeTraversals(Tree_TestCase.java:371)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- EmptyTryeditorTreeTraversals -->
  <testcase classname="testCases.Tree_TestCase" name="EmptyTryeditorTypesofBT" time="4.168">
    <failure type="java.lang.AssertionError" message="Alert is not present">
      <![CDATA[java.lang.AssertionError: Alert is not present
at org.testng.Assert.fail(Assert.java:111)
at testCases.Tree_TestCase.EmptyTryeditorTypesofBT(Tree_TestCase.java:607)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- EmptyTryeditorTypesofBT -->
  <testcase classname="testCases.Tree_TestCase" name="EmptyTryeditorTypesofTrees" time="2.598">
    <failure type="java.lang.AssertionError" message="Alert is not present">
      <![CDATA[java.lang.AssertionError: Alert is not present
at org.testng.Assert.fail(Assert.java:111)
at testCases.Tree_TestCase.EmptyTryeditorTypesofTrees(Tree_TestCase.java:289)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- EmptyTryeditorTypesofTrees -->
  <testcase classname="testCases.Tree_TestCase" name="IBST" time="0.836"/>
  <testcase classname="testCases.Tree_TestCase" name="IBT" time="1.49"/>
  <testcase classname="testCases.Tree_TestCase" name="ImpinBT" time="0.711"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityABT" time="3.528"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityABT" time="2.855"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityBST" time="3.173"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityBST" time="3.327"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityBT" time="2.437"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityBT" time="4.721"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityBinTreeTrav" time="2.818"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityBinTreeTrav" time="3.667"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityIBST" time="1.609"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityIBST" time="8.577"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityIBT" time="1.987"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityIBT" time="1.749"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityImpinBT" time="1.712"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityImpinBT" time="2.202"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityOverview" time="1.665"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityOverview" time="1.37"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityTYpesofTrees" time="2.076"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityTYpesofTrees" time="1.614"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityTerm" time="1.712"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityTerm" time="2.487"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityTraversalsIllus" time="2.31"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityTraversalsIllus" time="1.82"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityTreeTraversals" time="2.564"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityTreeTraversals" time="4.199"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityTypesofBT" time="1.534"/>
  <testcase classname="testCases.Tree_TestCase" name="InvalidTryHereFunctionalityTypesofBT" time="2.097"/>
  <testcase classname="testCases.Tree_TestCase" name="LogOut" time="0.899"/>
  <testcase classname="testCases.Tree_TestCase" name="NavtoOverviewofTrees" time="1.248"/>
  <testcase classname="testCases.Tree_TestCase" name="NavtoTryherepg" time="4.108"/>
  <testcase classname="testCases.Tree_TestCase" name="NavtoTryherepgABT" time="2.904"/>
  <testcase classname="testCases.Tree_TestCase" name="NavtoTryherepgBST" time="3.017"/>
  <testcase classname="testCases.Tree_TestCase" name="NavtoTryherepgBT" time="3.648"/>
  <testcase classname="testCases.Tree_TestCase" name="NavtoTryherepgBinTreeTrav" time="1.43"/>
  <testcase classname="testCases.Tree_TestCase" name="NavtoTryherepgIBST" time="2.43"/>
  <testcase classname="testCases.Tree_TestCase" name="NavtoTryherepgIBT" time="1.517"/>
  <testcase classname="testCases.Tree_TestCase" name="NavtoTryherepgImpinBT" time="2.286"/>
  <testcase classname="testCases.Tree_TestCase" name="NavtoTryherepgTermimology" time="1.771"/>
  <testcase classname="testCases.Tree_TestCase" name="NavtoTryherepgTravelsIllus" time="2.427"/>
  <testcase classname="testCases.Tree_TestCase" name="NavtoTryherepgTreeTraversals" time="3.533"/>
  <testcase classname="testCases.Tree_TestCase" name="NavtoTryherepgTypesofBT" time="2.824"/>
  <testcase classname="testCases.Tree_TestCase" name="NavtoTryherepgTypesofTrees" time="1.457"/>
  <testcase classname="testCases.Tree_TestCase" name="Practice" time="1.071"/>
  <testcase classname="testCases.Tree_TestCase" name="Terminologies" time="0.588"/>
  <testcase classname="testCases.Tree_TestCase" name="TravelsIllus" time="0.661"/>
  <testcase classname="testCases.Tree_TestCase" name="TreeTraversals" time="0.737"/>
  <testcase classname="testCases.Tree_TestCase" name="TypesofBT" time="0.505"/>
  <testcase classname="testCases.Tree_TestCase" name="TypesofTrees" time="1.325"/>
  <testcase classname="testCases.Tree_TestCase" name="ValidTryHereFunctionalityABT" time="3.426"/>
  <testcase classname="testCases.Tree_TestCase" name="ValidTryHereFunctionalityBST" time="2.275"/>
  <testcase classname="testCases.Tree_TestCase" name="ValidTryHereFunctionalityBT" time="3.183"/>
  <testcase classname="testCases.Tree_TestCase" name="ValidTryHereFunctionalityBinTreeTrav" time="4.13"/>
  <testcase classname="testCases.Tree_TestCase" name="ValidTryHereFunctionalityIBST" time="3.356"/>
  <testcase classname="testCases.Tree_TestCase" name="ValidTryHereFunctionalityIBT" time="3.531"/>
  <testcase classname="testCases.Tree_TestCase" name="ValidTryHereFunctionalityImpinBT" time="2.999"/>
  <testcase classname="testCases.Tree_TestCase" name="ValidTryHereFunctionalityOverview" time="3.846"/>
  <testcase classname="testCases.Tree_TestCase" name="ValidTryHereFunctionalityTerm" time="1.973"/>
  <testcase classname="testCases.Tree_TestCase" name="ValidTryHereFunctionalityTraversalsIllus" time="4.254"/>
  <testcase classname="testCases.Tree_TestCase" name="ValidTryHereFunctionalityTreeTraversals" time="2.86"/>
  <testcase classname="testCases.Tree_TestCase" name="ValidTryHereFunctionalityTypesofBT" time="2.455"/>
  <testcase classname="testCases.Tree_TestCase" name="ValidTryHereFunctionalityTypesoftrees" time="1.868"/>
</testsuite> <!-- Default test -->
