<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Cricket" failures="6" tests="36" name="testCases.Register_TestCase" time="166.170" errors="0" timestamp="2025-01-11T22:28:06 CST" skipped="18">
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="5.795">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="ToLogin" time="2.690"/>
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="3.154"/>
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="2.637"/>
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="10.433">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="5.919">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="4.732">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="4.419">
    <failure message="expected [password_mismatch:The two password fields didn’t match.] but found [Invalid Password]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [password_mismatch:The two password fields didn’t match.] but found [Invalid Password]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.Register_TestCase.InvalidRegister(Register_TestCase.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
    <system-out>
      <![CDATA[Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\InvalidRegister.png]]>
    </system-out>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="5.731">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="ToLogin" time="2.128"/>
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="3.366">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="3.773"/>
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="4.028">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="6.598">
    <failure message="expected [password_mismatch:The two password fields didn’t match.] but found [Invalid Username ]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [password_mismatch:The two password fields didn’t match.] but found [Invalid Username ]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.Register_TestCase.InvalidRegister(Register_TestCase.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
    <system-out>
      <![CDATA[Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\InvalidRegister.png]]>
    </system-out>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="4.753"/>
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="3.234">
    <failure message="expected [password_mismatch:The two password fields didn’t match.] but found [Invalid Password]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [password_mismatch:The two password fields didn’t match.] but found [Invalid Password]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.Register_TestCase.InvalidRegister(Register_TestCase.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
    <system-out>
      <![CDATA[Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\InvalidRegister.png]]>
    </system-out>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="4.780">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="4.428">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="2.863"/>
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="4.730">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="4.658">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="6.778"/>
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="2.981"/>
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="4.670">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="5.877">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="5.395"/>
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="5.233">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="1.963"/>
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="2.932">
    <failure message="expected [password_mismatch:The two password fields didn’t match.] but found [The user Is already Registered]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [password_mismatch:The two password fields didn’t match.] but found [The user Is already Registered]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.Register_TestCase.InvalidRegister(Register_TestCase.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
    <system-out>
      <![CDATA[Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\InvalidRegister.png]]>
    </system-out>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="4.755">
    <failure message="expected [password_mismatch:The two password fields didn’t match.] but found [Invalid Username ]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [password_mismatch:The two password fields didn’t match.] but found [Invalid Username ]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.Register_TestCase.InvalidRegister(Register_TestCase.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
    <system-out>
      <![CDATA[Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\InvalidRegister.png]]>
    </system-out>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="4.990">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="2.799">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="10.088">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="2.804"/>
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="5.666">
    <skipped/>
  </testcase> <!-- InvalidRegister -->
  <testcase classname="testCases.Register_TestCase" name="InvalidRegister" time="4.390">
    <failure message="expected [password_mismatch:The two password fields didn’t match.] but found [The user Is already Registered]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [password_mismatch:The two password fields didn’t match.] but found [The user Is already Registered]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.Register_TestCase.InvalidRegister(Register_TestCase.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
    <system-out>
      <![CDATA[Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\InvalidRegister.png]]>
    </system-out>
  </testcase> <!-- InvalidRegister -->
  <system-out>
    <![CDATA[Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\InvalidRegister.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\InvalidRegister.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\InvalidRegister.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorABT.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorBST.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorBT.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorBinTreeTrav.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorIBST.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorIBT.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorImpinBT.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorOverview.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorTerminologies.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorTravelsIllus.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorTreeTraversals.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorTypesofBT.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorTypesofTrees.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\InvalidRegister.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\InvalidRegister.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\InvalidRegister.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorABT.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorBST.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorBT.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorBinTreeTrav.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorIBST.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorIBT.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorImpinBT.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorOverview.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorTerminologies.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorTravelsIllus.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorTreeTraversals.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorTypesofBT.png
Screenshot saved at: C:\Users\12017\Desktop\MurugaKaapathu\AS_testNG\screenshots\EmptyTryeditorTypesofTrees.png]]>
  </system-out>
</testsuite> <!-- testCases.Register_TestCase -->
